2023-09-11 18:00:05,230 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-09-11 18:00:05,231 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Configure stats pid to 22168
2023-09-11 18:00:05,231 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Loading settings from C:\Users\srika\.config\wandb\settings
2023-09-11 18:00:05,231 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Loading settings from C:\Users\srika\Dynamic_Pricing\wandb\settings
2023-09-11 18:00:05,231 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-11 18:00:05,231 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'sac_dp.py', 'program': 'C:\\Users\\srika\\Dynamic_Pricing\\sac_dp.py'}
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\srika\Dynamic_Pricing\wandb\run-20230911_180005-8jon8y5c\logs\debug.log
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\srika\Dynamic_Pricing\wandb\run-20230911_180005-8jon8y5c\logs\debug-internal.log
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:init():547] calling init triggers
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'exp_name': 'sac_d', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'SAC_DP', 'wandb_entity': 'dp_rl', 'capture_video': False, 'env_id': 'DP', 'total_timesteps': 1000000, 'buffer_size': 1000000, 'gamma': 0.99, 'tau': 0.005, 'batch_size': 256, 'learning_starts': 5000.0, 'policy_lr': 0.0003, 'q_lr': 0.001, 'policy_frequency': 2, 'target_network_frequency': 1, 'noise_clip': 0.5, 'alpha': 0.2, 'autotune': True}
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:init():596] starting backend
2023-09-11 18:00:05,233 INFO    MainThread:22168 [wandb_init.py:init():600] setting up manager
2023-09-11 18:00:05,239 INFO    MainThread:22168 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-09-11 18:00:05,244 INFO    MainThread:22168 [wandb_init.py:init():606] backend started and connected
2023-09-11 18:00:05,248 INFO    MainThread:22168 [wandb_init.py:init():703] updated telemetry
2023-09-11 18:00:05,249 INFO    MainThread:22168 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-09-11 18:00:06,663 ERROR   MainThread:22168 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-11 18:00:07,114 ERROR   MainThread:22168 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1152, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-11 18:00:08,127 WARNING MsgRouterThr:22168 [router.py:message_loop():77] message_loop has been closed
